## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [3]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [5]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpt.csv")

In [7]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [8]:
## call the last 5 rows
dfbi.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [9]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
57934,48,141,'PADRES DR',31412931.0,106204050.0,1.0,12.0,1997.0,5,2.0,7,6,7,N,N,NaN
37042,48,29,'NOLAN ST ROW',29254532.0,98285170.0,1.0,11.0,1972.0,5,2.0,7,7,7,N,N,NaN
25977,48,201,'BRAYS BAYOU',29424400.0,95224004.0,1.0,12.0,1978.0,2,1.0,7,7,7,7,N,NaN
86784,51,710,'I-64WB; I-264WB & Ramps',36504451.0,76113779.0,1.0,11.0,1992.0,4,2.0,6,6,6,N,N,NaN
60818,48,497,'US 81/287',33032076.0,97284310.0,NaN,2.0,1972.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2590,47,157,'I40 MAINLINE',35152081.0,89403570.0,NaN,11.0,2000.0,6,2.0,NaN,NaN,NaN,NaN,NaN,NaN
55193,48,283,'DRAW',28273900.0,99035644.0,2.0,9.0,1950.0,1,1.0,5,5,6,6,N,NaN
77341,51,5,'KARNES CREEK',37472561.0,79532253.0,1.0,1.0,1954.0,4,2.0,7,6,6,8,N,NaN
51390,48,203,'STARKEY CREEK',32291996.0,94235630.0,1.0,1.0,1965.0,1,19.0,N,N,N,5,6,NaN
95342,53,53,'GULCH NO 2',47024820.0,122023303.0,1.0,7.0,1957.0,7,2.0,7,6,5,N,N,NaN
95484,53,33,'MILITARY RD',47210662.0,122174512.0,1.0,11.0,1960.0,5,2.0,7,6,7,N,N,NaN
25811,48,201,'IH 45 & SH 35',29414926.0,95172525.0,1.0,11.0,1977.0,3,2.0,6,6,7,N,N,NaN
60972,48,485,'FAIRWAY BLVD',33522928.0,98333942.0,NaN,7.0,2003.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3235,47,187,'I840-LL / FRY RD.',35490738.0,86574536.0,NaN,9.0,2011.0,6,2.0,NaN,NaN,NaN,NaN,NaN,NaN
71970,49,45,'SALT FLATS DRAINAGE',40441630.0,113491583.0,1.0,1.0,1983.0,9,19.0,N,N,N,7,5,1.0
62908,48,201,'US 59 & SH 288',29440600.0,95221488.0,NaN,12.0,1979.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
36720,48,29,'SALITRILLO CREEK',29282153.0,98161077.0,1.0,11.0,1962.0,1,2.0,7,6,6,7,N,NaN
14241,48,267,'RM 1674',30300240.0,99562128.0,1.0,1.0,1975.0,5,2.0,7,7,7,N,N,NaN
84961,51,191,'BEAVER CREEK',36392709.0,82060503.0,1.0,17.0,1971.0,1,19.0,N,N,N,5,7,NaN
7644,48,439,'COTTONWOOD CREEK',32553993.0,97033953.0,1.0,14.0,2007.0,1,19.0,N,N,N,6,7,NaN

In [14]:
## get basic overview of the data
## what datatypes do the different columns hold? 
## how many rows and columns are there
dfbi.info

<bound method DataFrame.info of        STATE_CODE_001  COUNTY_CODE_003          FEATURES_DESC_006A  \
0                  47              189                    'BRANCH'
1                  47              189                    'BRANCH'
2                  47              189                    'BRANCH'
3                  47              189                  'OVERFLOW'
4                  47              189           'HURRICANE CREEK'
...               ...              ...                         ...
99995              53               39               'TROUT CREEK'
99996              53               65            'COLVILLE RIVER'
99997              53               77                     'DRAIN'
99998              53               53               'LEACH CREEK'
99999              53               75  'SOUTH FORK PALOUSE RIVER'

          LAT_016     LONG_017  OWNER_022  FUNCTIONAL_CLASS_026  \
0      35595580.0   86115051.0        2.0                   8.0
1      35575281.0   86103402.0        2.0                   8.0
2      36062250.0   86245507.0        2.0                   8.0
3      36060931.0   86245689.0        2.0                   8.0
4      36031626.0   86251979.0        2.0                   8.0
...           ...          ...        ...                   ...
99995  45595604.0  121314080.0        2.0                   7.0
99996  48103246.0  117434719.0        2.0                   7.0
99997  46195400.0  120161800.0        2.0                   9.0
99998  47122326.0  122305265.0        4.0                  14.0
99999  46461734.0  117141254.0        2.0                   9.0

       YEAR_BUILT_027  STRUCTURE_KIND_043A  STRUCTURE_TYPE_043B DECK_COND_058  \
0              1965.0                    2                 19.0             N
1              1930.0                    2                 19.0             N
2              1935.0                    2                 19.0             N
3              1960.0                    2                 19.0             N
4              1970.0                    3                  2.0             6
...               ...                  ...                  ...           ...
99995          1956.0                    2                  1.0             6
99996          1960.0                    3                  2.0             5
99997          1965.0                    7                  2.0             7
99998          1981.0                    3                 19.0             N
99999          1963.0                    5                  4.0             5

      SUPERSTRUCTURE_COND_059 SUBSTRUCTURE_COND_060 CHANNEL_COND_061  \
0                           N                     N                7
1                           N                     N                7
2                           N                     N                7
3                           N                     N                7
4                           5                     5                8
...                       ...                   ...              ...
99995                       6                     5                8
99996                       6                     6                8
99997                       4                     4                8
99998                       N                     N                8
99999                       6                     7                7

      CULVERT_COND_062  PIER_PROTECTION_111
0                    5                  NaN
1                    7                  NaN
2                    5                  NaN
3                    7                  NaN
4                    N                  NaN
...                ...                  ...
99995                N                  NaN
99996                N                  NaN
99997                N                  NaN
99998                7                  NaN
99999                N                  NaN

[100000 rows x 16 columns]>

In [23]:
type(dfbi.STATE_CODE_001)

pandas.Series

### Which column has the most missing data...just a quick estimate?
Pier_protection_111

In [20]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [21]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
25400,48,201,'HIGH LEVEL RD',29433902.0,95160072.0,1.0,11.0,1973.0,5,2.0,6,6,6,N,N,NaN
75217,50,27,'WEST RIVER',43201431.0,72470711.0,1.0,6.0,1967.0,3,19.0,N,N,N,6,6,NaN
68106,48,121,'None',33102504.0,97052375.0,NaN,17.0,2017.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
49500,48,139,'DRAW',32312704.0,96584284.0,1.0,2.0,1994.0,1,19.0,N,N,N,7,6,NaN
20112,48,183,'RABBIT CREEK RELIEF',32260537.0,94490108.0,1.0,1.0,1967.0,1,2.0,6,7,6,7,N,NaN
51753,48,365,'MARTIN CREEK',32161985.0,94263084.0,1.0,7.0,1956.0,1,2.0,7,7,6,7,N,NaN
90895,51,35,'HANKS BRANCH',36345680.0,80512460.0,66.0,8.0,1939.0,1,4.0,6,7,7,6,N,NaN
48360,48,121,'FM 156 & BNSF RAILROAD',33185277.0,97104675.0,1.0,1.0,1958.0,4,2.0,6,6,6,N,N,NaN
24606,48,201,'HIRAM CLARKE RD',29391468.0,95264649.0,1.0,12.0,2001.0,5,2.0,7,7,7,N,N,NaN
14262,48,267,'NORTH LLANO RIVER',30301788.0,99540991.0,1.0,8.0,1950.0,4,3.0,6,6,5,6,N,1.0

In [22]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [32]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [31]:
## call FEATURES_DESC_006A as a series using square bracket notation

dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [33]:
## what are the unique owner codes?
dfbi["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

In [ ]:
#identifiers of parties that are in charge of bridges?